djangoBackend/djangoBackend/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
import Team_5.views as views

urlpatterns = [
    path('admin', admin.site.urls),
    path('', views.index_view),
    path('index.html', views.index_view),
    path('login.html', views.login_view),
    path('services.html', views.services_view),
    path('searching.html', views.searching_view),
    path('posting.html', views.posting_view),
    path('rent_out.html', views.renting_view),
    path('approve_listing.html', views.approve_listing_view),
    path('offers.html', views.offers_view),
    path('remove_user.html', views.remove_user_view),
    path('send_offer.html/<str:listing_id>', views.send_offer_view, name="send_offer"),
    path('sign-up.html', views.sign_up_view),
    path('logout', views.logout_view),
    path('determine_route_index', views.determine_route_index_view),
    path('query', views.search_view),
    path('favorites.html', views.favorite_list),
    path('<str:listing_id>', views.single_view, name="single"),
    path('favorite/<str:listing_id>', views.favorite_post, name="favorite_post"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoBackend/Team_5/models.py
from djongo import models
from datetime import datetime
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from djongo.models import ObjectIdField


# Create your models here.

class CustomUser(AbstractUser):
    pass
    user_type = models.CharField(max_length=200)

    def __str__(self):
        return self.username

    def get_user_type(self):
        return self.user_type

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(CustomUser, self).__init__(*args, **kwargs)


class Listing(models.Model):
    pass
    _id = models.ObjectIdField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # Delete when user is deleted
    title = models.CharField(max_length=200)
    address1 = models.CharField(max_length=200)
    address2 = models.CharField(max_length=200, blank=True)
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=200)
    year = models.CharField(max_length=4)
    description = models.TextField(blank=True)
    zipcode = models.CharField(max_length=10)
    category = models.CharField(max_length=20)
    bedrooms = models.IntegerField()
    bathrooms = models.DecimalField(max_digits=2, decimal_places=1)
    price = models.IntegerField()
    photo_main = models.ImageField(upload_to='images/', blank=True)
    photo_1 = models.ImageField(upload_to='images/', blank=True)
    photo_2 = models.ImageField(upload_to='images/', blank=True)
    photo_3 = models.ImageField(upload_to='images/', blank=True)
    photo_4 = models.ImageField(upload_to='images/', blank=True)
    photo_5 = models.ImageField(upload_to='images/', blank=True)
    photo_6 = models.ImageField(upload_to='images/', blank=True)
    favorite = models.ManyToManyField(CustomUser, related_name='favorite', blank=True)  # Listing has many CustomUsers
    # and a CustomUser can be member of different Listings
    list_date = models.DateTimeField(default=datetime.now, blank=True)
    listing_type = models.CharField(max_length=200)
    objects = models.DjongoManager()

    def __str__(self):
        return self.title

    def values(self):
        return self.title, self.address1


class Offer(models.Model):
    email = models.EmailField(max_length=255)
    phone = models.BigIntegerField()
    offer = models.BigIntegerField()
    comment = models.TextField(blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # Delete when user is deleted
    listing_id = models.CharField(max_length=255)

    def __str__(self):
        return self.email

djangoBackend/Team_5/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render
from django.http import Http404
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserCreationForm, ListingForm, SendOfferForm
from .models import Listing, CustomUser, Offer
import uuid
import os
from django.conf import settings
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.shortcuts import render, redirect
from bson import ObjectId
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse, HttpResponseRedirect


# from .models import
# Create your views here.
def index_view(request):
    # Render function takes request argument
    # return HTML
    return render(request, 'main_app/index.html')


def login_view(request):
    # return sign-up.html
    if request.method == 'GET':
        return render(request, 'main_app/login.html')

    elif request.method == "POST":
        name = request.POST.get('username', '')
        passW = request.POST.get('password', '')

        user = authenticate(username=name, password=passW)
        if user is not None:
            login(request, user)
            return redirect('/index.html')
        else:
            return render(request, 'main_app/login.html')

    # return login.html
    return render(request, 'main_app/login.html')


def logout_view(request):
    logout(request)
    return render(request, 'main_app/index.html')


def services_view(request):
    # return services.html
    return render(request, 'main_app/services.html')


def searching_view(request):
    queryset_list = Listing.objects.order_by('-list_date')
    for list2 in queryset_list:
        print("from searching:",type(list2.pk))
    context = {
        'listings': queryset_list,
        'values': request.GET
    }

    return render(request, 'main_app/searching.html', context)


def favorite_list(request):

    user = request.user
    favorite_posts = user.favorite.all()
    context = {
        'favorite_posts': favorite_posts
        }
    return render(request, 'main_app/favorites.html', context)


def favorite_post(request, listing_id):
    list_id = ObjectId(listing_id)
    listing = Listing.objects.get(pk=list_id)
    is_favorite = False
    try:
        if listing.favorite.get(id=request.user.id):
            listing.favorite.remove(request.user)
    except ObjectDoesNotExist:
        listing.favorite.add(request.user)
        is_favorite = True

    context = {
        'listing': listing,
        'is_favorite': is_favorite
    }
    return render(request, 'main_app/single.html', context)


def single_view(request, listing_id):
    # return single.html
    listing_id = ObjectId(listing_id)
    try:
        listing = Listing.objects.get(pk=listing_id)
        is_favorite = False
        user = request.user
        try:
            if listing.favorite.get(id=user.id):
                is_favorite = True
                request.session['listing_id'] = str(listing.pk)
        except ObjectDoesNotExist:
            pass

    except Listing.DoesNotExist:
        raise Http404("Listing does not exists")

    context = {
        'listing': listing,
        'is_favorite': is_favorite
    }
    return render(request, 'main_app/single.html', context)


def posting_view(request):

    if request.method == 'GET':
        return render(request, 'main_app/posting.html')

    elif request.method == "POST":
        user = request.user
        form = ListingForm(request.POST)

        if form.is_valid():

            listing = form.save(commit=False)
            images = request.FILES.getlist('images')

            if images:
                ext = images[0].name.split('.')[-1]
                filename = "%s.%s" % (uuid.uuid4(), ext)
                listing.photo_main = filename
                path = default_storage.save(settings.MEDIA_ROOT+filename, ContentFile(images[0].read()))
                del images[0]
            if images:
                ext = images[0].name.split('.')[-1]
                filename = "%s.%s" % (uuid.uuid4(), ext)
                listing.photo_1 = filename
                path = default_storage.save(settings.MEDIA_ROOT + filename, ContentFile(images[0].read()))
                del images[0]
            if images:
                ext = images[0].name.split('.')[-1]
                filename = "%s.%s" % (uuid.uuid4(), ext)
                listing.photo_2 = filename
                path = default_storage.save(settings.MEDIA_ROOT + filename, ContentFile(images[0].read()))
                del images[0]
            if images:
                ext = images[0].name.split('.')[-1]
                filename = "%s.%s" % (uuid.uuid4(), ext)
                listing.photo_3 = filename
                path = default_storage.save(settings.MEDIA_ROOT + filename, ContentFile(images[0].read()))
                del images[0]
            if images:
                ext = images[0].name.split('.')[-1]
                filename = "%s.%s" % (uuid.uuid4(), ext)
                listing.photo_4 = filename
                path = default_storage.save(settings.MEDIA_ROOT + filename, ContentFile(images[0].read()))
                del images[0]
            if images:
                ext = images[0].name.split('.')[-1]
                filename = "%s.%s" % (uuid.uuid4(), ext)
                listing.photo_5 = filename
                path = default_storage.save(settings.MEDIA_ROOT + filename, ContentFile(images[0].read()))
                del images[0]
            if images:
                ext = images[0].name.split('.')[-1]
                filename = "%s.%s" % (uuid.uuid4(), ext)
                listing.photo_6 = filename
                path = default_storage.save(settings.MEDIA_ROOT + filename, ContentFile(images[0].read()))
                del images[0]

            listing.save()
            return redirect('/services.html')

        return redirect('/posting.html')

    # return posting.html
    return render(request, 'main_app/posting.html')


def renting_view(request):

    if request.method == 'GET':
        return render(request, 'main_app/rent_out.html')

    elif request.method == "POST":
        user = request.user
        form = ListingForm(request.POST)
        print(request.POST)
        if form.is_valid():
            print("Is valid")
            listing = form.save(commit=False)
            images = request.FILES.getlist('images')

            if images:
                ext = images[0].name.split('.')[-1]
                filename = "%s.%s" % (uuid.uuid4(), ext)
                listing.photo_main = filename
                path = default_storage.save(settings.MEDIA_ROOT+filename, ContentFile(images[0].read()))
                del images[0]
            if images:
                ext = images[0].name.split('.')[-1]
                filename = "%s.%s" % (uuid.uuid4(), ext)
                listing.photo_1 = filename
                path = default_storage.save(settings.MEDIA_ROOT + filename, ContentFile(images[0].read()))
                del images[0]
            if images:
                ext = images[0].name.split('.')[-1]
                filename = "%s.%s" % (uuid.uuid4(), ext)
                listing.photo_2 = filename
                path = default_storage.save(settings.MEDIA_ROOT + filename, ContentFile(images[0].read()))
                del images[0]
            if images:
                ext = images[0].name.split('.')[-1]
                filename = "%s.%s" % (uuid.uuid4(), ext)
                listing.photo_3 = filename
                path = default_storage.save(settings.MEDIA_ROOT + filename, ContentFile(images[0].read()))
                del images[0]
            if images:
                ext = images[0].name.split('.')[-1]
                filename = "%s.%s" % (uuid.uuid4(), ext)
                listing.photo_4 = filename
                path = default_storage.save(settings.MEDIA_ROOT + filename, ContentFile(images[0].read()))
                del images[0]
            if images:
                ext = images[0].name.split('.')[-1]
                filename = "%s.%s" % (uuid.uuid4(), ext)
                listing.photo_5 = filename
                path = default_storage.save(settings.MEDIA_ROOT + filename, ContentFile(images[0].read()))
                del images[0]
            if images:
                ext = images[0].name.split('.')[-1]
                filename = "%s.%s" % (uuid.uuid4(), ext)
                listing.photo_6 = filename
                path = default_storage.save(settings.MEDIA_ROOT + filename, ContentFile(images[0].read()))
                del images[0]

            listing.save()
            return redirect('/services.html')

        return redirect('/rent_out.html')

    # return posting.html
    return render(request, 'main_app/rent_out.html')


def approve_listing_view(request):
    # return approve_listing.html
    return render(request, 'main_app/approve_listing.html')


def offers_view(request):

    user = request.user
    queryset_list = Offer.objects.order_by('user_id')
    queryset_list = queryset_list.filter(user_id=user.id)
    sent_listings = []
    # Get the sent listing objects
    for item in queryset_list:
        try:
            listing_id = ObjectId(item.listing_id)
            listing = Listing.objects.get(pk=listing_id)
            sent_listings.append(listing)
        except ObjectDoesNotExist:
            continue
    # Get all Listings that a person received offers for
    querylist_received = Listing.objects.filter(user_id=user.id)
    received_listings = []
    for item in querylist_received:
        try:
            listing_id = str(item.pk)
            one_listing = Offer.objects.filter(listing_id=listing_id)
            # If multiple offers on a single listing
            if one_listing.count() > 1:

djangoBackend/Team_5/templates/main_app/posting.html
<!DOCTYPE html>
<head>
    <title>Add Listing</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    {% load static %}
    <link href="{% static 'css/bootstrap.css' %}" rel='stylesheet' type='text/css' />
    <link href="{% static 'css/mystyle.css' %}" rel='stylesheet' type='text/css' />
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>

<body>
<!-- mian-content -->
<section class="mian-content">
    <!-- /header-top-->
    <div class="header-top">
        <div class="container">
            <header class="mainheader py-3">
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <h1><a class="navbar-brand" href="index.html">Team 5</a></h1>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-toggle"
                            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse navbar-toggle justify-content-end" id="navbarNavAltMarkup">
                        <ul class="navbar-nav">
                            <li><a class="nav-link text-uppercase" href="/index.html">Home</a></li>
                            <li><a class="nav-link text-uppercase" href="/services.html">services</a></li>
                        </ul>
                        <div class="top-info text-left">
                            <ul>
                                {% if user.is_authenticated %}
                                <li class="number-phone"><a class="nav-link request text-uppercase font-weight-bold" href="/logout" >Logout</a></li>
                                {% else %}
                                <li class="number-phone"><a class="nav-link request text-uppercase font-weight-bold" href="/login.html" >Login</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </nav>
            </header>
            <!-- /header-top-->
        </div>

    </div>
    <!-- //header-top-->
</section>
<div class="container">
    <div class="row">
        <h3 class="listing">Add a listing</h3>
    </div>
    <div class="row">
        <form method="POST" class="form" enctype="multipart/form-data">
            {% csrf_token %}
                <div class="column">
                    <input id="user" name="user" type="hidden" value="{{user.id}}">

                    <label>Title</label><span class="required">*</span>
                    <input id="title" name="title" type="text" required="required">

                    <label for="Description">Description</label>
                    <textarea id="description" name="description" rows="5"></textarea>

                    <label>Address Line 1</label><span class="required">*</span>
                    <input id="address1" name="address1" type="text">

                    <label>Address Line 2</label>
                    <input id="address2" name="'address2" type="text">

                    <label>City</label><span class="required">*</span>
                    <input id="city" name="city" type="text">

                    <label>State</label><span class="required">*</span>
                    <input id="state" name="state" type="text">

                </div>
            <div class="column">
                <label>Zip Code</label><span class="required">*</span>
                <input id="zipcode" name="zipcode" type="text" maxlength="6">

                <label for="id_category">Category</label><span class="required">*</span>

                <select id="id_category" name="category" class="selectpicker">
                    <option>---</option>
                    <option value="House">House</option>
                    <option value="Apartment">Apartment</option>
                    <option value="Room">Room</option>
                    <option value="Building">Building</option>
                </select>

                <label for="id_bedrooms">Bedrooms</label><span class="required">*</span>
                <select id="id_bedrooms" name="bedrooms" class="selectpicker">
                    <option>---</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5+">5+</option>
                </select>

                <label for="id_bathrooms">Bathrooms</label><span class="required">*</span>
                <select id="id_bathrooms" name="bathrooms" class="selectpicker">
                    <option>---</option>
                    <option value="1">1</option>
                    <option value="1.5">1.5</option>
                    <option value="2">2</option>
                    <option value="2.5">2.5</option>
                    <option value="3">3</option>
                    <option value="3.5">3.5</option>
                    <option value="4">4</option>
                    <option value="5+">5+</option>
                </select>
                <label>Year Built</label><span class="required">*</span>
                <input name="year" id="year" type="text"><br>

                <label>Price</label><span class="required">*</span>
                <input name="price" id="price" type="text"><br>

                <label for="images">Upload images</label>
                <input type="file" id="images" name="images" accept="image/*" multiple>

                <button type="submit" class="btn btn-info">Submit listing</button>
            </div>
        </form>

    </div>
</div>
</div>

<!-- //features -->
</body>

<!--/footer-->
<footer class="pymd-5 py-4" id="footer">
    <div class="container">
        <div class="inner-sec py-md-5 py-3">
            <div class="row mb-md-4 mb-md-3">
                <div class="col-lg-3 col-md-6 social-info text-left">
                    <h3 class="tittle1 foot mb-md-5 mb-4 text-white">Contact</h3>
                    <p>2020 fall semester </p>
                    <p class="my-2">CMPE 202 Team 5 </p>
                </div>
                <div class="col-md-6 social-info text-left">
                    <h3 class="tittle1 foot mb-md-5 mb-4 text-white">About Us</h3>
                    <p>We are a 3-member team which aims to develop a user-friendly website related to houses busineses.
                        Our features and functions are going to severs three kinds of people, they are realtor who is a
                        representatives of people, Individuals who handles their own houses, and lastly, Adminstrators who
                        is going to maintain this website.</p>

                </div>
            </div>
        </div>
    </div>
</footer>
<!--//footer-->
</html>

djangoBackend/Team_5/templates/main_app/rent_out.html
<!DOCTYPE html>
<head>
    <title>Add Listing</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    {% load static %}
    <link href="{% static 'css/bootstrap.css' %}" rel='stylesheet' type='text/css' />
    <link href="{% static 'css/mystyle.css' %}" rel='stylesheet' type='text/css' />
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>

<body>
<!-- mian-content -->
<section class="mian-content">
    <!-- /header-top-->
    <div class="header-top">
        <div class="container">
            <header class="mainheader py-3">
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <h1><a class="navbar-brand" href="index.html">Team 5</a></h1>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-toggle"
                            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse navbar-toggle justify-content-end" id="navbarNavAltMarkup">
                        <ul class="navbar-nav">
                            <li><a class="nav-link text-uppercase" href="/index.html">Home</a></li>
                            <li><a class="nav-link text-uppercase" href="/services.html">services</a></li>
                        </ul>
                        <div class="top-info text-left">
                            <ul>
                                {% if user.is_authenticated %}
                                <li class="number-phone"><a class="nav-link request text-uppercase font-weight-bold" href="/logout" >Logout</a></li>
                                {% else %}
                                <li class="number-phone"><a class="nav-link request text-uppercase font-weight-bold" href="/login.html" >Login</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </nav>
            </header>
            <!-- /header-top-->
        </div>

    </div>
    <!-- //header-top-->
</section>
<div class="container">
    <div class="row">
        <h3 class="listing">Add a listing</h3>
    </div>
    <div class="row">
        <form method="POST" class="form" enctype="multipart/form-data">
            {% csrf_token %}
                <div class="column">
                    <input id="user" name="user" type="hidden" value="{{user.id}}">
                    <input id="listing_type" name="listing_type" type="hidden" value="rental">
                    <label>Title</label><span class="required">*</span>
                    <input id="title" name="title" type="text" required="required">

                    <label for="Description">Description</label>
                    <textarea id="description" name="description" rows="5"></textarea>

                    <label>Address Line 1</label><span class="required">*</span>
                    <input id="address1" name="address1" type="text">

                    <label>Address Line 2</label>
                    <input id="address2" name="'address2" type="text">

                    <label>City</label><span class="required">*</span>
                    <input id="city" name="city" type="text">

                    <label>State</label><span class="required">*</span>
                    <input id="state" name="state" type="text">

                </div>
            <div class="column">
                <label>Zip Code</label><span class="required">*</span>
                <input id="zipcode" name="zipcode" type="text" maxlength="6">

                <label for="id_category">Category</label><span class="required">*</span>

                <select id="id_category" name="category" class="selectpicker">
                    <option>---</option>
                    <option value="House">House</option>
                    <option value="Apartment">Apartment</option>
                    <option value="Room">Room</option>
                    <option value="Building">Building</option>
                </select>

                <label for="id_bedrooms">Bedrooms</label><span class="required">*</span>
                <select id="id_bedrooms" name="bedrooms" class="selectpicker">
                    <option>---</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5+">5+</option>
                </select>

                <label for="id_bathrooms">Bathrooms</label><span class="required">*</span>
                <select id="id_bathrooms" name="bathrooms" class="selectpicker">
                    <option>---</option>
                    <option value="1">1</option>
                    <option value="1.5">1.5</option>
                    <option value="2">2</option>
                    <option value="2.5">2.5</option>
                    <option value="3">3</option>
                    <option value="3.5">3.5</option>
                    <option value="4">4</option>
                    <option value="5+">5+</option>
                </select>
                <label>Year Built</label><span class="required">*</span>
                <input name="year" id="year" type="text"><br>

                <label>Price</label><span class="required">*</span>
                <input name="price" id="price" type="text"><br>

                <label for="images">Upload images</label>
                <input type="file" id="images" name="images" accept="image/*" multiple>

                <button type="submit" class="btn btn-info">Submit listing</button>
            </div>
        </form>

    </div>
</div>
</div>

<!-- //features -->
</body>

<!--/footer-->
<footer class="pymd-5 py-4" id="footer">
    <div class="container">
        <div class="inner-sec py-md-5 py-3">
            <div class="row mb-md-4 mb-md-3">
                <div class="col-lg-3 col-md-6 social-info text-left">
                    <h3 class="tittle1 foot mb-md-5 mb-4 text-white">Contact</h3>
                    <p>2020 fall semester </p>
                    <p class="my-2">CMPE 202 Team 5 </p>
                </div>
                <div class="col-md-6 social-info text-left">
                    <h3 class="tittle1 foot mb-md-5 mb-4 text-white">About Us</h3>
                    <p>We are a 3-member team which aims to develop a user-friendly website related to houses busineses.
                        Our features and functions are going to severs three kinds of people, they are realtor who is a
                        representatives of people, Individuals who handles their own houses, and lastly, Adminstrators who
                        is going to maintain this website.</p>

                </div>
            </div>
        </div>
    </div>
</footer>
<!--//footer-->
</html>